### ISSUE TITLE
额外的拓展

### ISSUE THREAD

**Issue by longsfreedom** [evanryuu/tw-dark-usecase#1]
大佬，想要增加其的拓展性，就像antd的配置主题token一样，能支持传入某个特定的变量颜色来改变默认主题色。
例如：
```
:root {
    --v-white: #fff;
}

@media (prefers-color-scheme: dark) {
    :root {
        --v-white: #273246;
    }
}
//tailwind.config.js
module.exports = {
    theme: {
        extend: {
            colors: {
                white: "var(--v-white)",
            },
        },
    },
};

```
上面是默认的某个颜色的暗亮配色，如果我想要在以下使用，类似这样做能够改变默认主题配色中的特定颜色该怎么做：
```
<ConfigProvider
    theme={{
      token: {
        light-white: '#00b96b',
        dark-white:  '#02b96b',
      },
    }}
  >
    <App>
    </App>
  </ConfigProvider>
```

**Comment by evanryuu** [comment]
不好意思过了这么久才回复😂

我觉得这是一个很好的想法！由于我们这套颜色切换是基于css变量的，所以如果是我要做这个的话，我会希望能够改变ConfigProvider的子元素的token，所以我会用React的cloneElement来实现这个功能。

代码如下
<img width="548" alt="image" src="https://github.com/user-attachments/assets/bf31e5e5-f06d-427a-aa37-27e8f85fa719">

效果如下
<img width="491" alt="image" src="https://github.com/user-attachments/assets/d85aaf35-4f97-4a57-a627-81519b3fd4d2">

具体的代码实现我已经推到了[feat/multi-themes](https://github.com/evanryuu/tw-dark-usecase/tree/feat/multi-themes)的这个分支，如果你感兴趣的话也可以拉下来看看具体实现😄

**Comment by longsfreedom** [comment]
多谢了，和我最后的做法类似😂

**Comment by evanryuu** [comment]
nice work!
